import React from "react";

export default function Community() {
  return (
    <div className="w-full min-h-screen bg-background p-4 md:p-8 flex flex-col font-sans select-text">
      <div className="max-w-4xl w-full mx-auto text-left">
        <h1 className="text-4xl font-extrabold tracking-tight text-zinc-950 mb-4">Community</h1>
        <p className="text-lg text-muted-foreground font-medium mb-10">
          Discover courses generated by others and share your custom curriculums.
        </p>

        <div className="bg-card border border-border rounded-2xl p-12 text-center shadow-sm">
          <div className="w-20 h-20 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-6 select-none">
            <svg className="w-10 h-10 text-primary" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
            </svg>
          </div>
          <h2 className="text-2xl font-bold text-zinc-900 mb-2">Community Hub Coming Soon</h2>
          <p className="text-zinc-500 mb-0 max-w-md mx-auto leading-relaxed">
            We are building a public library where you can publish and clone top-rated AI-generated modules. Stay tuned!
          </p>
        </div>
      </div>
    </div>
  );
}
